### ISSUE TITLE
Inserting a module causes the reader page to 404

### ISSUE THREAD

**Issue by 360fusion** [bwein-net/contao-gallery#1] opened 2024-04-02 10:44 UTC
It looks like when I add {{insert_module::16}} to a template it will casue the gallery reader page to show a 404 page.

I have these in my footer to load in additional content.

**Comment by rabauss** [comment] 2024-04-04 16:20
What kind of module is the ID 16 in your system? In what kind of template do you want to use the insert tag?

The reader uses the autoitem of the url so if you call the url in which you have insert the reader it will not work without the detail alias - this is not supported in the extension. but I think also not possible for news or event readers.

**Comment by 360fusion** [comment] 2024-04-05 08:26
the modules were navigation links and events links.

I did have some issues with the events pages showing 404 too. 

I'll have a look at the detail alias.

Thanks

**Comment by rabauss** [comment] 2024-04-06 15:59
I suspect the problem is not related to my extension. Your planned scenario is not intended in Contao or you have misunderstood a configuration of Contao - especially with regard to detail pages. Therefore, I will close this issue

**Closed as completed by rabauss** 2024-04-06 15:59 UTC
